apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: demo-app
          image: ghcr.io/dsmeneses17/demo-openshift@sha256:80661858143783b536d3681396d93b1761ba1da852301131cc26ecec85a3e5a8
          ports:
            - containerPort: 8080